export default [
  {
    name: 'mercury',
    planet: {
      x: 40,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.03,
      color: '',
      map: 'mercury_2k.jpg',
      bumpMap: 'mercury_2k.jpg',
      // bumpMap: true,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: false,
  },
  {
    name: 'venus',
    planet: {
      x: 70,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.02,
      color: '',
      map: 'venus_2k.jpg',
      bumpMap: 'venus_2k.jpg',
      // bumpMap: true,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: false,
  },

  {
    name: 'earth',
    planet: {
      x: 100,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.01,
      color: '',
      map: 'earth_daymap_2k.jpg',
      bumpMap: 'earth_daymap_2k.jpg',
      // bumpMap: true,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: [
      {
        name: 'clouds',
        x: 0,
        y: 0,
        z: 0,
        r: 1.01,
        spin: 0.008,
        orbit: 0,
        color: '#fff',
        map: false,
        bumpMap: false,
        bumpScale: 0,
        transparent: true,
        alphaMap: 'earth_clouds_2k.jpg',
        opacity: 1,
        shininess: 0,
      },
    ],
    rings: false,
  },

  {
    name: 'mars',
    planet: {
      x: 130,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.008,
      color: '',
      map: 'mars_2k.jpg',
      bumpMap: 'mars_2k.jpg',
      // bumpMap: true,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: false,
  },
  {
    name: 'jupiter',
    planet: {
      x: 160,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.003,
      color: '',
      map: 'jupiter_2k.jpg',
      // bumpMap: 'jupiter_2k.jpg',
      bumpMap: false,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: false,
  },
  {
    name: 'saturn',
    planet: {
      x: 190,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.001,
      color: '',
      map: 'saturn_2k.jpg',
      bumpMap: false,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: {
      x: 0,
      y: 0,
      z: 0,
      inner: 1.2,
      outer: 2,
      spin: 0,
      orbit: 0,
      color: '',
      map: 'saturn_rings_2k.jpg',
      bumpMap: false,
      bumpScale: 0,
      transparent: true,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
  },
  {
    name: 'uranus',
    planet: {
      x: 220,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.0008,
      color: '',
      map: 'uranus_2k.jpg',
      bumpMap: false,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: false,
  },

  {
    name: 'neptune',
    planet: {
      x: 250,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.0004,
      color: '',
      map: 'neptune_2k.jpg',
      bumpMap: false,
      bumpScale: 0.4,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },

    layers: false,
    rings: false,
  },

  {
    name: 'pluto',
    planet: {
      x: 280,
      y: 0,
      z: 0,
      r: 10,
      spin: 0.01,
      orbit: 0,
      orbitSpeed: 0.001,
      color: '',
      map: 'pluto_2k.jpg',
      bumpMap: 'pluto_bump_2k.jpg',
      bumpScale: 1,
      transparent: false,
      alphaMap: false,
      opacity: 1,
      shininess: 0,
    },
    layers: false,
    rings: false,
  },
]
